---
ID: "701c6437-c1ef-4af9-b05b-40820b344a1a"
Parent: "8bb2144c-0b1f-4ef9-9841-31c247de494f"
Template: "8bb2144c-0b1f-4ef9-9841-31c247de494f"
Path: /sitecore/templates/Foundation/SitecoreMods/Authorization/Types/BasicAuth/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230731T154653Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
