---
ID: "19ca9384-98a9-4f7b-9e9a-ecc308eb1c55"
Parent: "f118cf5f-05f6-4cb6-8215-1e22a6f18f76"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Foundation/SitecoreMods/Authorization/Types/ApiKey/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230731T153636Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
