---
ID: "f5985c05-5192-4d80-8d5e-2a1621deeb7b"
Parent: "5b4ce364-b272-4924-9290-c8f83479d949"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Foundation/SitecoreMods/Authorization/Types/OAuth2ClientCredentialsGrant/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230731T155133Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
