---
ID: "3a18c50e-53a3-480b-a6bd-571ba7313161"
Parent: "b8b93e64-c9a9-41cd-bf1d-3cea658bbc57"
Template: "b8b93e64-c9a9-41cd-bf1d-3cea658bbc57"
Path: /sitecore/templates/Foundation/SitecoreMods/Authorization/Types/OAuth2PasswordCredentialsGrant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230731T154904Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
