---
ID: "84c837dd-9e58-4c5c-b77e-731ddf1ecb8c"
Parent: "b8b93e64-c9a9-41cd-bf1d-3cea658bbc57"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Foundation/SitecoreMods/Authorization/Types/OAuth2PasswordCredentialsGrant/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230731T154900Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
